= Agenda+
:toc: macro
:toc-title: Conteúdo
:toclevels: 3

[.lead]
Um projeto de agenda desenvolvido para a disciplina Tópicos Especiais de
Programação.

toc::[]

== Instalação e execução
=== Dependências
É fortemente recomendado utilizar a versão mais recente do python, em versões
anteriores o sistema pode funcionar mas não é testado por isso não nós
responsabilizamos, caso haja falhas se executando em versões anteriores do
python.

A lista de dependências pode ser encontrada abaixo, mas ela é proveniente do
arquivo link:requirements.txt[]
----
# Front-end
flet
requests
python-dotenv

# Back-end
flask
kink
pytest
python-dotenv
----

=== Instalando dependências
O modo mais simples de instalação das dependências é usando o `pip`. Além disso
é fortemente recomendado usar um ambiente virtual. +
Veja: <<usando-venv>>

Para instalar todas as dependências execute:

    python -m pip install -r requirements.txt

É possível também instalar as dependências apenas do front-end ou apenas do
back-end. Para instalar as dependências do front-end somente, execute:

    python -m pip install -r frontend/requirements.txt

Para instalar as do back-end é com:

    python -m pip install -r backend/requirements.txt

WARNING: A instalação acima fará com que as dependências do projeto sejam
instaladas globalmente o que pode não ser o melhor resultado.

[#usando-venv]
==== Usando um ambiente virtual
O modo recomendado para instalação das dependências é usando um
https://docs.python.org/pt-br/3/library/venv.html[ambiente virtual].
O processo pode ser resumido nos seguintes passos:

===== Unix/macOS
    $ python -m venv .venv

===== Windows
    > python -m venv .venv

Após a crianção do ambiente virtual é necessário ativá-lo.

===== Unix/macOS
    $ . .venv/bin/activate

===== Windows
    > .venv\Scripts\activate

Com isso o ambiente virtual está pronto para ser utilizado caso queira para
confirmar isso no prompt mostrará o nome do ambiente virtual ativo nele
sair/desativar o ambiente virtual só basta executar o comando `deactivate`.

=== Executando o sistema
Para executar o sistema é necessário iniciar individualmente o back-end e depois
o front-end do sistema.

Para iniciar a execução do back-end:

    python -m backend

E para o front-end execute:

    flet run -dm frontend

É importe que se inicie primeiro o back-end e depois o front-end porque o
front-end depende de dados que são servidos pelo back-end.

== Autores e licença
.Autores
- Igor <igor.menino23@gmail.com>
- Jonatha Gabriel <jonathagabrielns@gmail.com>
- Kéwen <kewensilva58@gmail.com>

O projeto pode ser encontrado em https://github.com/j0ng4b/AgendaPlus e foi
licenciado sob os termos da `BSD-3-Clause` para mais detalhes visite o
arquivo link:LICENSE[].

== Conclusão e agradecimentos
