= Agenda+
:toc: macro
:toc-title: Conteúdo
:toclevels: 3

[.lead]
Um projeto de agenda desenvolvido para a disciplina Tópicos Especiais de
Programação.

toc::[]

== Instalação e execução
=== Dependências
É fortemente recomendado utilizar a versão mais recente do python, em versões
anteriores o sistema pode funcionar mas não é testado por isso não nós
responsabilizamos, caso haja falhas se executando em versões anteriores do
python.

A lista de dependências pode ser encontrada abaixo, mas ela é proveniente do
arquivo link:requirements.txt[]
----
# Front-end
flet
requests
python-dotenv

# Back-end
flask
kink
pytest
python-dotenv
----

=== Instalando dependências
O modo mais simples de instalação das dependências é usando o `pip`. Além disso
é fortemente recomendado usar um ambiente virtual. +
Veja: <<usando-venv>>

Para instalar todas as dependências execute:

    python -m pip install -r requirements.txt

É possível também instalar as dependências apenas do front-end ou apenas do
back-end. Para instalar as dependências do front-end somente, execute:

    python -m pip install -r frontend/requirements.txt

Para instalar as do back-end é com:

    python -m pip install -r backend/requirements.txt

WARNING: A instalação acima fará com que as dependências do projeto sejam
instaladas globalmente o que pode não ser o melhor resultado.

[#usando-venv]
==== Usando um ambiente virtual
O modo recomendado para instalação das dependências é usando um
https://docs.python.org/pt-br/3/library/venv.html[ambiente virtual].
O processo pode ser resumido nos seguintes passos:

===== Unix/macOS
    $ python -m venv .venv

===== Windows
    > python -m venv .venv

Após a crianção do ambiente virtual é necessário ativá-lo.

===== Unix/macOS
    $ . .venv/bin/activate

===== Windows
    > .venv\Scripts\activate

Com isso o ambiente virtual está pronto para ser utilizado caso queira para
confirmar isso no prompt mostrará o nome do ambiente virtual ativo nele
sair/desativar o ambiente virtual só basta executar o comando `deactivate`.

=== Executando o sistema
Para executar o sistema é necessário iniciar individualmente o back-end e depois
o front-end do sistema.

Para iniciar a execução do back-end primeiro copie o arquivo
`.env.backend.sample` para `.env.backend,` esse arquivo é onde reside as
configurações do back-end como porta de execução, tipo de ambiente entre outras.

É recomendado copiar o arquivo `.env.backend.sample` pois ele já apresenta
alguns __defaults__ razoáveis sendo apenas necessário definir as chaves secretas
para a geração dos tokens de autenticação.

NOTE: Para saber como gerar uma chave secreta aleatória veja <<secret-keys>>.

    python -m backend

Para iniciar a execução do front-end primeiro copie o arquivo
`.env.frontend.sample` para `.env.frontend,` esse arquivo é onde reside as
configurações do front-end.

É recomendado copiar o arquivo `.env.frontend.sample` pois ele já apresenta
alguns __defaults__ razoáveis. Após isso inicie o front-end com:

    flet run -dm frontend

É importe que se inicie primeiro o back-end e depois o front-end porque o
front-end depende de dados que são servidos pelo back-end.

[#secret-keys]
==== Gerando chaves secretas aleatórias
É importante gerar uma chave secreta aleatória pois assim garante a segurança na
autenticação dos usuários além de não permitir acesso a dados de um usuário por
outro usuário mal intencionado.

WARNING: Gerar uma chave secreta é importante pois sem ela os tokens não são
gerados corretamente e nem tão pouco são seguros.

A chave secreta também dever ser aleatória para que dificulte a vida dos
__hackers__. O método mais fácil de gerar uma chave secreta aleatória é usando o
próprio `Python` através do módulo `secrets`.

Exemplo de como gerar uma chave secreta de 32 bytes:

    python -c "import secrets; print(secrets.token_hex(32))"

Com a chave gerada basta copiá-la para onde ela será usada.

==== Usando HTTPS no servidor de desenvolvimento do back-end
Para que o front-end consiga se comunicar com o back-end, enviando os cookies
automaticamente, é necessário uma de duas opções:

1. Modificar a variável de ambiente `VERIFY_SSL_CERTIFICATES` do front-end
autorizando o front-end a ignorar a verificação de certificados SSL. Esse é o
método mais simples, mas menos seguro.

2. Se executando o back-end com um servidor de desenvolvimento é necessário
gerar um certificado e fazer com que ele seja confiável, esse é um processo
totalmente dependente de plataforma. Uma vez que você tenha um certificado e uma
chave é possível definir as variáveis de ambiente `SERVER_SSL_CERTIFICATE` e
`SERVER_SSL_CERTIFICATE_KEY`.

WARNING: Quando em um ambiente de produção o valor da variável de ambiente
`VERIFY_SSL_CERTIFICATES` é totalmente ignorando, forçando a verificação de
certificados SSL.


== Autores e licença
.Autores
- Jonatha Gabriel <jonathagabrielns@gmail.com>
- Kéwen <kewensilva58@gmail.com>

O projeto pode ser encontrado em https://github.com/j0ng4b/AgendaPlus e foi
licenciado sob os termos da `BSD-3-Clause` para mais detalhes visite o
arquivo link:LICENSE[].

